name: cache-warmer
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger og-images generation
        run: curl -s -o /dev/null -D - https://www.pristinevxo.se/api/og-image/start.png && curl -s -o /dev/null -D - https://www.pristinevxo.se/api/og-image/pricelist.png
